### ISSUE TITLE
Combine DefeatZealots and DefeatZealots Blink?

### ISSUE THREAD

**Issue by SoyGema** [4rChon/sc2-ai-mini-games#2]
Hi 4rChon!
Congrats on your work on PySC2 minigames!! 👍 
I am working on a curated list of minigames and would love to add your work. I am testing all minigames and have a question 

Why don't you **combine** DefeatZealots and DefeatZealots Blink **map into one**, making a state (t+n) in which stalkers are able to Blink? I mean do you have any reason to separate this into two mini-games ? Are you doing this to compare results in both mini-games so a single agent can learn about Blink in Stalkers ?

Thanks so much for the time dedicated to solve this issue, please keep up your excellent work . 💯 
If you have any problem with adding your work to the repo let me know 

Thanks Benjamin!

**Comment by 4rChon** [comment]
Hi SoyGema,
Thanks for taking interest!

Using Stalkers with Blink vs without requires a different policy. Blink is an upgrade that comes into effect a bit later in the game. Before then, it is likely that Stalkers would have already been used in a fight without Blink. 

If one were to train an agent to use Blink Stalkers, and then simply mask the Blink action when it cannot be used, there is no guarantee that the result would be as effective as one trained specifically without the Blink action.

Finally, until there is a dedicated micro-managing simulator, I think it's important to provide as many different configurations of the environment as possible, even if they are not used.

I hope I answered your questions! Otherwise, please let me know!

I would really love to contribute more mini-games to the list, but related work has pulled me away from the mini-games aspect. Hopefully I can contribute more to this project in the future.

Thanks again Gema!

**Comment by 4rChon** [comment]
Hi,

I have reconsidered your question and realised that I've approached this backwards. I've come to agree that combining them makes sense, since the Blink action can always be excluded from the action set before training starts anyway - as if it was never an option in the first place - and then enabled later on, to simulate Blink being unlocked, if need be.

Thanks for the suggestion and the insight!

**Comment by SoyGema** [comment]
Ey Benjamin,
I do understand both ways of thinking. Now what I am propose might go that the mini-game could start without blinking and if the Stalker win it could re-start the mini game with the Blink ability .

However, I find this environment suitable for community !
Let me know if you evolve or change it somehow. In the meantime I will advance with other mini-games test. 
Feel also free to close the issue, as it has already been quite fruitful
And don´t hesitate to contact me in whatever you might need 

Best,
G

**Comment by SoyGema** [comment]
Ey !
Could you Please check the structure of the repo for insights and feedback??
[(https://github.com/SoyGema/pySC2-minigames)](url)
Do you think the mini game should have a initial image ?
Does the policy designing tips work for you?

thanks!

**Comment by 4rChon** [comment]
I think you can sum up the optimal policy more succintly by saying that the Stalkers should learn to kite and focus fire. If you think using gameplay terminology such as _kiting_ might be confusing to readers, then I suggest making the word itself a link to the definition. For example: [kiting](http://wiki.teamliquid.net/starcraft2/Kiting).

[This Liquipedia page](http://wiki.teamliquid.net/starcraft2/Definitions) contains a list of terminology which may be useful.

Other than that it looks good!

I think the initial image is very helpful, even to recognize the setup of the mini-game at a glance. I might make use of that idea myself :)
